pekko {
  actor {
    provider = "cluster"

    serialization-bindings {
      "com.conquerer.server.domain.common.JsonSerializable" = jackson-json
    }
  }

  remote {
    artery {
      canonical.hostname = "127.0.0.1"
      canonical.port = 2551
    }
  }

  cluster {
    seed-nodes = [
      "pekko://ConquererSystem@127.0.0.1:2551"
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
    sharding {
      # Custom settings for sharding if needed
      number-of-shards = 100
    }
  }

  persistence {
    journal.plugin = "jdbc-journal"
    snapshot-store.plugin = "jdbc-snapshot-store"
  }
}

jdbc-journal {
  use-shared-db = "db"
}

jdbc-snapshot-store {
  use-shared-db = "db"
}

jdbc-read-journal {
  use-shared-db = "db"
}

pekko-persistence-jdbc {
  shared-databases {
    db {
      profile = "slick.jdbc.PostgresProfile$"
      db {
        host = "localhost"
        url = "jdbc:postgresql://localhost:5432/conquerer"
        user = "postgres"
        password = "password"
        driver = "org.postgresql.Driver"
        numThreads = 5
        maxConnections = 5
        minConnections = 1
      }
    }
  }
}
